apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ressafri/test-delete-me-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCRo8Kxkm67Ee/PmIACEGrtsQZIhZhgsS1kWu7y91m5sQAAAKDsA4uk7AOL
    pAAAAAtzc2gtZWQyNTUxOQAAACCRo8Kxkm67Ee/PmIACEGrtsQZIhZhgsS1kWu7y91m5sQ
    AAAEBSbHMqmCcVFQ9Aeo/bQUyf/GmwKfwR4RPs/Jm2gXN2T5GjwrGSbrsR78+YgAIQau2x
    BkiFmGCxLWRa7vL3WbmxAAAAGHBlcnNvbmFsIG1hY2Jvb2sgcHJvZCBtMwECAwQF
    -----END OPENSSH PRIVATE KEY-----    
  insecureIgnoreHostKey: "false"
  enableLfs: "true"