---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmb-portfolio-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ressafri/test-delete-me.git
    targetRevision: HEAD
    path: cmb/environments/staging/cmb-portfolio
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - Validate=true
        - CreateNamespace=false