---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmb-feed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ressafri/test-delete-me-private.git
    targetRevision: HEAD
    path: cmb/environments/staging/cmb-feed
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
